version: "2"

services:
  kudu-master:
    container_name: kudu-master
    image: kudu-master
    ports:
      - 8051:8051
  kudu-tserver-1:
    container_name: kudu-tserver-1
    image: kudu-tserver
    depends_on:
      - kudu-master
    environment:
      - KUDU_MASTER=kudu-master
    ports:
      - 8052:8050
  kudu-tserver-2:
    container_name: kudu-tserver-2
    image: kudu-tserver
    depends_on:
      - kudu-master
    environment:
      - KUDU_MASTER=kudu-master
    ports:
      - 8055:8050
  kudu-tserver-3:
    container_name: kudu-tserver-3
    image: kudu-tserver
    depends_on:
      - kudu-master
    environment:
      - KUDU_MASTER=kudu-master
    ports:
      - 8056:8050
  kudu-client:
    container_name: kudu-client
    image: base-kudu
    ports:
      - 7777:7777
